### PR TITLE
fix: #464 use session to store search filter

### LINKED ISSUE #464: Host: Navigation changes the filter selection
When the filters are modified and the user navigates a challenge and returns to the challenges page, the filter selection goes off. 
Filters should remain intact.

As navigation moves away from the Host react app, keeping filter data in the store or react app will not be helpful. We might have to rely on session storage.

### PR DESCRIPTION
**Pull request by Abhinav-Chdhary**
# Title and Issue number 

Title :  Keep track of search filters while navigating between challenges

Issue No. : #464 

Code Stack :  JSX

Closes #464 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the Index.html file for my contribution

### CODE REVIEW

**Comment by Abhinav-Chdhary** [comment]
@sadanandpai I believe we would need a clear-filters button after this.

File: apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx [hunk 1]
```diff
@@ -13,13 +13,42 @@ interface Props {
...
+    }
+    return {
+      searchInput: '',
+      optionSelected: [],
+      selectedDifficulties: [],
+      isSegmentBtn1: false,
+      selectedChallengesByTags: [],
+      newChallenge: false,
+    };
+  };
```
Comment (sadanandpai) [inline apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx:37]: if `initialSearchFilters` has no dependency on the component, can we not move everything to util

**Review by sadanandpai — CHANGES_REQUESTED** [review]

File: apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx (hunk 1 above)
Comment (Abhinav-Chdhary) [reply apps/host/src/components/modules/challenges/challenge-grid/challenge-grid.tsx:37]: Okay, I'll try.
